name = "live"
main = "src/index.ts"
compatibility_date = "2023-10-30"
workers_dev = true
routes = ["https://rabbitmq.com/*", "https://www.rabbitmq.com/*", "https://live.rabbitmq.com/*"]

[site]
bucket = "./public"
